### ISSUE TITLE
Remote readsb?

### ISSUE THREAD

**Issue by FabioEight** [sdr-enthusiasts/docker-readsb-protobuf#152]
Hello,
I was wondering if it’s possible to use resdsb to capture data on a remote site and use a different host (same network) and use a different readsb + readsb sharing service containers to retrieve the data and push it to internet?
Assuming the remote host has a lower processing power, this could improve the performances on it?
Thanks!

**Comment by mikenye** [comment]
Hi @FabioEight,

This is indeed possible.

An example configuration would be:

**Remote site:**

```yaml
version: '2.0'

volumes:
  readsbpb_rrd:
  readsbpb_autogain:

services:
  readsb:
    image: ghcr.io/sdr-enthusiasts/docker-readsb-protobuf:latest
    tty: true
    container_name: readsb
    hostname: readsb
    restart: always
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8080:8080
      - 30005:30005
    environment:
      - TZ=Australia/Perth
      - READSB_DCFILTER=true
      - READSB_DEVICE_TYPE=rtlsdr
      - READSB_FIX=true
      - READSB_GAIN=autogain
      - READSB_LAT=-33.33333
      - READSB_LON=111.11111
      - READSB_MODEAC=true
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      - READSB_NET_ENABLE=true
    volumes:
      - readsbpb_rrd:/run/collectd
      - readsbpb_autogain:/run/autogain
    tmpfs:
      - /run/readsb:size=64M
      - /var/log:size=32M
```

**More Powerful Host:**

_Note that all of the RTLSDR-related environment variables have been removed, and a `READSB_NET_CONNECTOR` variable has been added to receive the beast data from the remote host._

```yaml
version: '2.0'

volumes:
  readsbpb_rrd:
  readsbpb_autogain:

services:
  readsb:
    image: ghcr.io/sdr-enthusiasts/docker-readsb-protobuf:latest
    tty: true
    container_name: readsb
    hostname: readsb
    restart: always
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8080:8080
      - 30005:30005
    environment:
      - TZ=Australia/Perth
      - READSB_STATS_RANGE=true
      - READSB_NET_ENABLE=true
      - READSB_NET_CONNECTOR=remote.host.ip.addr,30005,beast_in
    volumes:
      - readsbpb_rrd:/run/collectd
      - readsbpb_autogain:/run/autogain
    tmpfs:
      - /run/readsb:size=64M
      - /var/log:size=32M
```

Let me know how you go.

-Mike
