### ISSUE TITLE
Using Airspy Mini without Success

### ISSUE THREAD

**Issue by uakm2201** [sdr-enthusiasts/docker-readsb-protobuf#193]
Hello All

First thanks for this dev, I know, this could be a nightmare !!

Im' trying to use an airspy mini without success. Normally, it should a rtlsdr dongle (rt820) but is not detected ..

I've try to install air spy mini on the docker without more success. I'm pretty sure that I'm not so far ...

slush

Bus 001 Device 003: ID 1d50:60a1 OpenMoko, Inc. Airspy

What the best way to use it ?

**Comment by mikenye** [comment]
It looks like I'll need to include the [airspy_adsb](https://github.com/firestuff/adsb-tools) utility within the container somehow. Or possibly in a different container and have this container connect to the airspy container to pull the data in...

I don't have an airspy so this will be difficult to implement. I'll do some reading.

It might be worth joining the Discord server and asking if anyone else is using an airspy to see what they are doing.

**Comment by mikenye** [comment]
Hello @uakm2201,

I've put together a container for you that I think will work with your airspy mini.

I'm not able to test this as I don't own an airspy mini. Would you be willing to test the container for me?

You should be able to add the following to the `services:` section of your `docker-compose.yml` file:

```yaml
  airspy_adsb:
    build: https://github.com/sdr-enthusiasts/adsb_airspy.git#main
    tty: true
    container_name: airspy_adsb
    hostname: airspy_adsb
    restart: always
    environment:
      - AIRSPY_ADSB_VERBOSE=true
    devices:
      - /dev/bus/usb
```

You can then run `docker compose build`, and the container will build.

If you then run `docker compose up airspy_adsb`, the container should launch and run the `airspy_adsb` binary.

Could you please try this and send me the output?

If this works, you should be able to replace your `readsb_protobuf` container with this container.
