### ISSUE TITLE
Logs are filled with MLAT messages

### ISSUE THREAD

**Issue by courtarro** [sdr-enthusiasts/docker-readsb-protobuf#83]
I get a lot of entries like this in the Docker logs. I assume this is a good thing (a measurement of error), but it feels like an error (problem).

> Received MLAT timestamp error: 0 seconds!

Is it possible to quiet the log output to include only WARN level messages or above?

... or does this message actually indicate an error?

**Comment by kx1t** [comment]
Hi @courtarro ,
Is your SDR directly connected to the container, or is it connected remotely from another device?
Also, what is the architecture you are using?
Last, although your issue seems clear, it would be great to have a bit of those logs attached here, so we are sure that we're all looking at the same thing :)

Thanks!

**Comment by courtarro** [comment]
Heyo. This is an RPi4 with a RTL-SDR directly connected via USB. OS is the standard 64-bit version of Ubuntu Server 20.04. The RTL-SDR has a bias-powered 1090MHz LNA near the FlightAware-branded 1090MHz antenna.

I logged back in this morning after rebuilding the Docker container midday and those messages do not appear anywhere. Perhaps this is something that only appears when there are no aircraft around, like in the middle of the night? When I see the message again I'll send the full log.

What does the message actually mean? Is it indicative of an error?

For reference, here's my Docker Compose service definition:

```
  readsb:
    container_name: readsb
    image: ghcr.io/sdr-enthusiasts/docker-readsb-protobuf
    tty: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "8080:8080"
      - "30005:30005"
    environment:
      - TZ=America/New_York
      - READSB_DCFILTER=true
      - READSB_ENABLE_BIASTEE=true
      - READSB_DEVICE_TYPE=rtlsdr
      - READSB_FIX=true
      - READSB_GAIN=32
      - READSB_LAT=(redacted)
      - READSB_LON=(redacted)
      - READSB_MODEAC=true
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      - READSB_NET_ENABLE=true
      - INFLUXDBURL=(redacted)
      - INFLUXDB_V2=true
      - INFLUXDB_V2_BUCKET=(redacted)
      - INFLUXDB_V2_ORG=(redacted)
      - "INFLUXDB_V2_TOKEN=(redacted)"
    volumes:
      - readsbpb_rrd:/run/collectd
      - readsbpb_autogain:/run/autogain
    restart: always
```
